/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/card.vue')['default']
    CommentRow: typeof import('./src/components/commentRow.vue')['default']
    Edit: typeof import('./src/components/edit.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NIcon: typeof import('naive-ui')['NIcon']
    NProgress: typeof import('naive-ui')['NProgress']
    NSpin: typeof import('naive-ui')['NSpin']
    NThing: typeof import('naive-ui')['NThing']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabbar: typeof import('./src/components/tabbar.vue')['default']
    User: typeof import('./src/components/user.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanPopover: typeof import('vant/es')['Popover']
    VanRate: typeof import('vant/es')['Rate']
    VanTag: typeof import('vant/es')['Tag']
    View: typeof import('./src/components/view.vue')['default']
  }
}

// For TSX support
declare global {
  const Card: typeof import('./src/components/card.vue')['default']
  const CommentRow: typeof import('./src/components/commentRow.vue')['default']
  const Edit: typeof import('./src/components/edit.vue')['default']
  const NButton: typeof import('naive-ui')['NButton']
  const NIcon: typeof import('naive-ui')['NIcon']
  const NProgress: typeof import('naive-ui')['NProgress']
  const NSpin: typeof import('naive-ui')['NSpin']
  const NThing: typeof import('naive-ui')['NThing']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Tabbar: typeof import('./src/components/tabbar.vue')['default']
  const User: typeof import('./src/components/user.vue')['default']
  const VanButton: typeof import('vant/es')['Button']
  const VanCell: typeof import('vant/es')['Cell']
  const VanField: typeof import('vant/es')['Field']
  const VanIcon: typeof import('vant/es')['Icon']
  const VanPopover: typeof import('vant/es')['Popover']
  const VanRate: typeof import('vant/es')['Rate']
  const VanTag: typeof import('vant/es')['Tag']
  const View: typeof import('./src/components/view.vue')['default']
}